name: Deploy Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  cancel-in-progress: false
  group: pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build docs
        run: pnpm --filter @lunchbox/docs run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
